name: build container image
on:
  push:
    branches:
      - 'main'
      - 'update/ci/docker/*'
      - 'update/docker/*'
    tags:
      - 'v*.*.*'

jobs:
  docker:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - amd
          - cuda
          - cpu
        include:
          - flavor: amd
            pip-extra-index-url: 'https://download.pytorch.org/whl/rocm5.2'
          - flavor: cuda
            pip-extra-index-url: ''
          - flavor: cpu
            pip-extra-index-url: 'https://download.pytorch.org/whl/cpu'
    runs-on: ubuntu-latest
    name: ${{ matrix.flavor }}
    env:
      PLATFORMS: 'linux/amd64,linux/arm64'
      DOCKERFILE: 'docker/Dockerfile'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository }}
            ${{ vars.DOCKERHUB_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,enable=true,prefix=sha-,format=short
          flavor: |
            latest=${{ matrix.flavor == 'cuda' && github.ref == 'refs/heads/main' }}
            suffix=-${{ matrix.flavor }},onlatest=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request' && vars.DOCKERHUB_REPOSITORY != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/tags/*' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: PIP_EXTRA_INDEX_URL=${{ matrix.pip-extra-index-url }}
          cache-from: |
            type=gha,scope=${{ github.ref_name }}-${{ matrix.flavor }}
            type=gha,scope=main-${{ matrix.flavor }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ matrix.flavor }}

      - name: Docker Hub Description
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/tags/*' && vars.DOCKERHUB_REPOSITORY != ''
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
